modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory (34 is current forge version)
license="ANS3.0NC" #mandatory
issueTrackerURL="https://github.com/lazyMods/Baubles/issues" #optional
[[mods]] #mandatory
modId="baubles" #mandatory
version="1.8.5" #mandatory
displayName="Baubles" #mandatory
logoFile="BLogo.png" #optional
credits="Azanor" #optional
authors="lazynessmind" #optional
description='''Adding a touch of bling to Minecraft'''